Repository mobi-production/ani-fe, pull requests merged in 2024-12, with the labels that each got.

#57 feat: 로그인/회원가입 페이지 msw 연동
  apps/web/src/__mock__/handler/auth.ts
  apps/web/src/__mock__/handler/index.ts
  apps/web/src/__mock__/handler/main.ts
  apps/web/src/__mock__/handler/mypage.ts
  apps/web/src/__mock__/types/auth.ts
  apps/web/src/entities/auth/lib/apis/index.ts
  apps/web/src/entities/auth/lib/apis/login.ts
  apps/web/src/entities/auth/lib/apis/signup.ts
  apps/web/src/entities/main/lib/apis/get-main-data.ts
  apps/web/src/entities/mypage/lib/apis/get-mypage-data.ts
  apps/web/src/entities/mypage/lib/apis/get-myprofile-data.ts
  apps/web/src/entities/mypage/lib/apis/put-myprofile.ts
  apps/web/src/features/auth/ui/login-modal/index.tsx
  apps/web/src/features/auth/ui/signup-modal/index.tsx
  apps/web/src/shared/config/constants/end-point.ts
  apps/web/src/shared/config/constants/querykey.ts
Labels: feat, D-2

#58 refactor: SDUI에 협의된 내용을 반영합니다.
  apps/web/src/__mock__/data/path.ts
  packages/sdu/README.md
  packages/sdu/src/components/bookmark/index.tsx
  packages/sdu/src/components/bulleted-list-item/example.json
  packages/sdu/src/components/bulleted-list-item/index.tsx
  packages/sdu/src/components/bulleted-list-item/style.json
  packages/sdu/src/components/callout/Callout.stories.tsx
  packages/sdu/src/components/callout/index.tsx
  packages/sdu/src/components/checkbox/Checkbox.stories.tsx
  packages/sdu/src/components/checkbox/Checkbox.tsx
  packages/sdu/src/components/checkbox/example.json
  packages/sdu/src/components/checkbox/index.tsx
  packages/sdu/src/components/common/ErrorBoundary.tsx
  packages/sdu/src/components/divider/Divider.stories.tsx
  packages/sdu/src/components/divider/index.tsx
  packages/sdu/src/components/file/File.stories.tsx
  packages/sdu/src/components/file/index.tsx
  packages/sdu/src/components/heading1/example.json
  packages/sdu/src/components/heading1/heading1-content.json
  packages/sdu/src/components/heading1/heading1-style.json
  packages/sdu/src/components/heading1/index.tsx
  packages/sdu/src/components/heading2/example.json
  packages/sdu/src/components/heading2/heading2-style.json
  packages/sdu/src/components/heading2/index.tsx
  packages/sdu/src/components/heading3/example.json
  packages/sdu/src/components/heading3/heading3-style.json
  packages/sdu/src/components/heading3/index.tsx
  packages/sdu/src/components/index.tsx
  packages/sdu/src/components/numbered-list-item/example.json
  packages/sdu/src/components/numbered-list-item/index.tsx
  packages/sdu/src/components/numbered-list-item/style.json
  packages/sdu/src/components/playground/Playground.stories.tsx
  packages/sdu/src/components/playground/Playground.tsx
  packages/sdu/src/components/quote/Quote.stories.tsx
  packages/sdu/src/components/quote/index.tsx
  packages/sdu/src/components/table-of-content/index.tsx
  packages/sdu/src/components/table/index.tsx
  packages/sdu/src/components/toggle/example.json
  packages/sdu/src/components/toggle/index.tsx
  packages/sdu/src/config/ChildrenDepthComponent.tsx
  packages/sdu/src/index.tsx
  packages/sdu/src/libs/uuid.ts
Labels: refactoring, D-1

#60 refactor: modal 컴포넌트를 변경합니다.
  apps/web/src/features/auth/ui/login-modal/LoginModal.stories.tsx
  apps/web/src/features/auth/ui/login-modal/index.tsx
  apps/web/src/features/auth/ui/signup-modal/SignupModal.stories.tsx
  apps/web/src/features/auth/ui/signup-modal/index.tsx
  apps/web/src/features/mypage/ui/profile-edit-modal/index.tsx
  apps/web/src/features/mypage/ui/withdrawal-modal/index.tsx
  apps/web/src/shared/hooks/use-funnel.tsx
  apps/web/src/shared/ui/modal/CommonModal.stories.tsx
  apps/web/src/shared/ui/modal/index.tsx
  apps/web/src/shared/ui/portal/Portal.tsx
  apps/web/src/shared/ui/portal/index.tsx
  apps/web/src/shared/ui/portal/modal/CommonModal.stories.tsx
  apps/web/src/shared/utils/extract-keys-from-object.ts
  apps/web/src/shared/utils/index.ts
  apps/web/src/shared/utils/wrap-with-app-router-context.tsx
  apps/web/src/views/PartFeedbackPage/PartFeedbackPage.stories.tsx
  apps/web/src/views/PartFeedbackPage/index.tsx
  apps/web/src/views/PathFeedbackPage/PathFeedbackPage.stories.tsx
  apps/web/src/views/path/ui/DetailPage/DetailPage.stories.tsx
  packages/ui/src/client.ts
  packages/ui/src/components/modal/Modal.stories.tsx
  packages/ui/src/components/modal/index.tsx
  packages/ui/src/hooks/use-portal.ts
  packages/ui/src/server.ts
Labels: refactoring, D-3

#59 refactor: fsd 경로에 맞게 리팩터링
  apps/web/app/mypage/page.tsx
  apps/web/app/page.tsx
  apps/web/src/__mock__/handler/auth.ts
  apps/web/src/__mock__/handler/main.ts
  apps/web/src/__mock__/handler/mypage.ts
  apps/web/src/__mock__/types/main.ts
  apps/web/src/__mock__/types/mypage.ts
  apps/web/src/entities/auth/model/index.ts
  apps/web/src/entities/auth/model/loginModalSchema.ts
  apps/web/src/entities/auth/model/signupModalSchema.ts
  apps/web/src/entities/mypage/model/myProfileEditSchema.ts
  apps/web/src/features/auth/api/index.ts
  apps/web/src/features/auth/api/login.ts
  apps/web/src/features/auth/api/signup.ts
  apps/web/src/features/auth/config/auth-config.ts
  apps/web/src/features/auth/model/index.ts
  apps/web/src/features/auth/model/use-auth-modal-store.ts
  apps/web/src/features/auth/model/use-auth.ts
  apps/web/src/features/auth/ui/login-modal/LoginModal.stories.tsx
  apps/web/src/features/auth/ui/login-modal/index.tsx
  apps/web/src/features/auth/ui/signup-modal/SignupModal.stories.tsx
  apps/web/src/features/auth/ui/signup-modal/index.tsx
  apps/web/src/features/mypage/api/delete-myprofile.ts
  apps/web/src/features/mypage/api/index.ts
  apps/web/src/features/mypage/api/put-myprofile.ts
  apps/web/src/features/mypage/model/apis.ts
  apps/web/src/features/mypage/ui/my-page-edit-button/MyPageEditButton.stories.tsx
  apps/web/src/features/mypage/ui/my-page-edit-button/index.tsx
  apps/web/src/features/mypage/ui/profile-edit-modal/ProfileEditModal.stories.tsx
  apps/web/src/features/mypage/ui/profile-edit-modal/index.tsx
  apps/web/src/features/mypage/ui/withdrawal-modal/WithdrawalModal.stories.tsx
  apps/web/src/features/mypage/ui/withdrawal-modal/index.tsx
  apps/web/src/shared/config/constants/end-point.ts
  apps/web/src/shared/config/constants/querykey.ts
  apps/web/src/shared/ui/header/index.tsx
  apps/web/src/views/main/api/get-main-data.ts
  apps/web/src/views/main/config/main-config.ts
  apps/web/src/views/main/model/apis.ts
  apps/web/src/views/main/ui/MainPage.stories.tsx
  apps/web/src/views/main/ui/index.tsx
  apps/web/src/views/mypage/api/get-mypage-data.ts
  apps/web/src/views/mypage/api/get-myprofile-data.ts
  apps/web/src/views/mypage/api/index.ts
  apps/web/src/views/mypage/config/apis.ts
  apps/web/src/views/mypage/model/apis.ts
  apps/web/src/views/mypage/ui/MyPage.stories.tsx
  apps/web/src/views/mypage/ui/index.tsx
Labels: refactoring, D-1

#61 feat: 질문 생성, 수정 레이아웃을 추가합니다.
  apps/web/src/entities/question/ui/user-path-drop-down/index.tsx
  apps/web/src/features/path/model/question-submit-schema.ts
  apps/web/src/features/quesion/ui/submit-question-section/SubmitQuestionSection.stories.tsx
  apps/web/src/features/quesion/ui/submit-question-section/index.tsx
  apps/web/src/views/question/api/get-question-detail.ts
  apps/web/src/views/question/ui/CreateQuestionPage/CreateQuestionPage.stories.tsx
  apps/web/src/views/question/ui/CreateQuestionPage/index.tsx
  apps/web/src/views/question/ui/EditQuestionPage/EditQuestionPage.stories.tsx
  apps/web/src/views/question/ui/EditQuestionPage/index.tsx
  apps/web/src/views/question/ui/QuestionListPage/QuestionListPage.stories.tsx
  apps/web/src/views/question/ui/QuestionListPage/index.tsx
  packages/ui/src/components/input/index.tsx
  packages/ui/src/components/input/variants.ts
  packages/ui/src/components/text-area/index.tsx
Labels: feat, D-2

#64 feat: SDU column_list 컴포넌트를 추가합니다.
  packages/sdu/README.md
  packages/sdu/package.json
  packages/sdu/src/components/code/index.tsx
  packages/sdu/src/components/column-list/CoulmnList.stories.tsx
  packages/sdu/src/components/column-list/example1.json
  packages/sdu/src/components/column-list/example2.json
  packages/sdu/src/components/column-list/index.tsx
  packages/sdu/src/components/index.tsx
  packages/sdu/src/index.tsx
Labels: refactoring, D-2

#65 feat: introduce내 모달을 추가합니다.
  apps/web/src/__mock__/data/path.ts
  apps/web/src/__mock__/handler/path.ts
  apps/web/src/entities/path/model/interruption-submit-schema.ts
  apps/web/src/features/path/api/delete-path-apply-cancle.ts
  apps/web/src/features/path/api/index.ts
  apps/web/src/features/path/api/post-path-apply.ts
  apps/web/src/features/path/config/path-config.ts
  apps/web/src/features/path/ui/ApplyButton.tsx
  apps/web/src/features/path/ui/CancleButton.tsx
  apps/web/src/features/path/ui/InterruptionButton.tsx
  apps/web/src/features/path/ui/apply-interription-modal/InterruptionModal.stories.tsx
  apps/web/src/features/path/ui/apply-interription-modal/index.tsx
  apps/web/src/features/path/ui/apply-modal/ApplyModal.stories.tsx
  apps/web/src/features/path/ui/apply-modal/index.tsx
  apps/web/src/features/path/ui/path-apply-button/PathApplyButton.stories.tsx
  apps/web/src/features/path/ui/path-apply-button/index.tsx
  apps/web/src/features/path/ui/path-cancle-button/PathCancleButton.stories.tsx
  apps/web/src/features/path/ui/path-cancle-button/index.tsx
  apps/web/src/shared/ui/dropdown-menu/index.tsx
  apps/web/src/views/path/api/get-path-introduce.ts
  apps/web/src/views/path/config/path-config.ts
  apps/web/src/views/path/ui/IntroducePage/index.tsx
  apps/web/src/widgets/path/ui/introduce/TopBanner.stories.tsx
  apps/web/src/widgets/path/ui/introduce/TopBanner.tsx
  packages/ui/src/components/icon/Icon.stories.tsx
  packages/ui/src/components/icon/variants.ts
Labels: feat, D-1

#66 feat: 로그인/회원가입 api를 추가합니다.
  .github/workflows/pr-check.yml
  .husky/pre-push
  apps/web/.env.sample
  apps/web/app/api/auth/[...nextauth]/route.ts
  apps/web/app/api/v1/auth/social/discord/callback/route.ts
  apps/web/app/error/page.tsx
  apps/web/app/layout.tsx
  apps/web/package.json
  apps/web/src/__mock__/types/auth.ts
  apps/web/src/auth.ts
  apps/web/src/entities/auth/model/index.ts
  apps/web/src/entities/auth/model/loginModalSchema.ts
  apps/web/src/entities/auth/model/tokenSchema.ts
  apps/web/src/features/auth/api/index.ts
  apps/web/src/features/auth/api/login.ts
  apps/web/src/features/auth/api/oauth-login.ts
  apps/web/src/features/auth/api/signup.ts
  apps/web/src/features/auth/config/auth-config.ts
  apps/web/src/features/auth/ui/login-modal/index.tsx
  apps/web/src/features/auth/ui/signup-modal/index.tsx
  apps/web/src/middleware.ts
  apps/web/src/shared/types/index.d.ts
  apps/web/src/shared/ui/dropdown-menu/index.tsx
  apps/web/src/shared/ui/header/Header.stories.tsx
  apps/web/src/shared/ui/header/index.tsx
  pnpm-lock.yaml
  turbo.json
Labels: feat, D-0

#67 feat: detail 페이지 타입 변경 및 api 연결
  apps/web/app/api/v1/auth/social/discord/callback/route.ts
  apps/web/app/path/[pathId]/page.tsx
  apps/web/src/__mock__/data/path.ts
  apps/web/src/features/auth/api/oauth-login.ts
  apps/web/src/shared/types/path.ts
  apps/web/src/shared/ui/header/index.tsx
  apps/web/src/views/path/api/get-path-introduce.ts
  apps/web/src/views/path/model/apis.ts
  apps/web/src/views/path/ui/IntroducePage/index.tsx
  apps/web/src/widgets/path/ui/introduce/CurriculumContent.tsx
  apps/web/src/widgets/path/ui/introduce/TopBanner.tsx
Labels: feat, D-2

#68 feat: cookie를 이용한 auth 기능을 추가합니다.
  apps/web/.env.sample
  apps/web/app/api/auth/[...nextauth]/route.ts
  apps/web/app/api/v1/auth/logout/route.ts
  apps/web/app/api/v1/auth/session/route.ts
  apps/web/app/api/v1/auth/social/discord/callback/route.ts
  apps/web/app/example.json
  apps/web/app/layout.tsx
  apps/web/app/page.tsx
  apps/web/package.json
  apps/web/src/__mock__/handler/auth.ts
  apps/web/src/auth.ts
  apps/web/src/entities/auth/model/index.ts
  apps/web/src/entities/auth/model/loginSchema.ts
  apps/web/src/entities/auth/model/signupSchema.ts
  apps/web/src/features/auth/api/get-access-token.ts
  apps/web/src/features/auth/api/get-role.ts
  apps/web/src/features/auth/api/index.ts
  apps/web/src/features/auth/api/local-login.ts
  apps/web/src/features/auth/api/local-signup.ts
  apps/web/src/features/auth/api/login.ts
  apps/web/src/features/auth/api/oauth-callback.ts
  apps/web/src/features/auth/api/oauth-login.ts
  apps/web/src/features/auth/api/sign-out.ts
  apps/web/src/features/auth/api/signup.ts
  apps/web/src/features/auth/config/auth-config.ts
  apps/web/src/features/auth/model/auth-store.ts
  apps/web/src/features/auth/model/index.ts
  apps/web/src/features/auth/model/use-auth-modal-store.ts
  apps/web/src/features/auth/model/use-auth.ts
  apps/web/src/features/auth/ui/login-modal/LoginModal.stories.tsx
  apps/web/src/features/auth/ui/login-modal/index.tsx
  apps/web/src/features/auth/ui/signup-modal/SignupModal.stories.tsx
  apps/web/src/features/auth/ui/signup-modal/index.tsx
  apps/web/src/features/path/ui/apply-modal/index.tsx
  apps/web/src/middleware.ts
  apps/web/src/shared/config/api/axios.ts
  apps/web/src/shared/config/api/index.ts
  apps/web/src/shared/config/api/numbers.ts
  apps/web/src/shared/config/api/storage-keys.ts
  apps/web/src/shared/libs/query-client.ts
  apps/web/src/shared/libs/session.ts
  apps/web/src/shared/types/index.d.ts
  apps/web/src/shared/types/tanstack-query.ts
  apps/web/src/shared/ui/header/Header.stories.tsx
  apps/web/src/shared/ui/header/index.tsx
  apps/web/src/views/path/api/get-path-introduce.ts
  apps/web/src/views/path/config/path-config.ts
  apps/web/src/views/path/ui/DetailPage/DetailPage.stories.tsx
  apps/web/src/widgets/path/ui/introduce/TopBanner.stories.tsx
  apps/web/src/widgets/path/ui/sidebar/InformationBlock.tsx
  pnpm-lock.yaml
Labels: refactoring, D-0

#69 feat: 에러 fallback 페이지를 추가합니다.
  .github/auto_assign.yml
  apps/web/app/not-found.tsx
  apps/web/public/webp/question.webp
  apps/web/src/views/error/ui/ErrorFallback.stories.tsx
  apps/web/src/views/error/ui/index.tsx
  config/libs/tailwind.config.cjs
  packages/ui/src/components/icon/variants.ts
Labels: feat, D-0
