Repository mobi-production/ani-fe, pull requests merged in 2024-11, with the labels that each got.

#1 feat: RadioGroup을 추가합니다.
  apps/web/app/example.json
  apps/web/app/page.tsx
  apps/web/package.json
  packages/ui/package.json
  packages/ui/src/components/atom/Button.stories.ts
  packages/ui/src/components/atom/Button.tsx
  packages/ui/src/components/atom/radio-group/RadioGroup.stories.tsx
  packages/ui/src/components/atom/radio-group/RadioGroup.tsx
  packages/ui/src/components/atom/radio-group/example.json
  packages/ui/src/components/renderComponents.tsx
  packages/ui/src/index.ts
  packages/ui/src/styles/globals.css
Labels: feat

#2 feat: Typography를 추가합니다.
  apps/web/app/page.tsx
  config/libs/tailwind.config.cjs
  package.json
  packages/ui/.storybook/main.ts
  packages/ui/.storybook/preview-head.html
  packages/ui/.storybook/preview.ts
  packages/ui/eslint.config.js
  packages/ui/package.json
  packages/ui/src/components/atom/Button.tsx
  packages/ui/src/components/atom/typography/Typography.tsx
  packages/ui/src/components/atom/typography/Typogrpahy.stories.ts
  packages/ui/src/components/atom/typography/variants.ts
  packages/ui/src/index.ts
  packages/ui/vite.config.js
  pnpm-lock.yaml
  turbo.json
Labels: feat

#3 refactor: RadioGroup type을 분류합니다.
  .eslintrc.js
  apps/web/.eslintrc
  apps/web/.eslintrc.js
  apps/web/app/layout.tsx
  apps/web/app/page.tsx
  apps/web/package.json
  apps/web/src/__mock__/handler/index.ts
  apps/web/src/__mock__/handler/member.ts
  apps/web/src/__mock__/http.ts
  apps/web/tsconfig.json
  config/es-config/index.js
  config/es-config/library.js
  config/es-config/next.js
  config/es-config/package.json
  config/es-config/react-internal.js
  package.json
  packages/ui/.eslintrc.cjs
  packages/ui/eslint.config.js
  packages/ui/package.json
  packages/ui/src/components/atom/radio-group/RadioGroup.stories.tsx
  packages/ui/src/components/atom/radio-group/RadioGroup.tsx
  packages/ui/src/components/atom/typography/Typography.tsx
  packages/ui/src/components/atom/typography/Typogrpahy.stories.ts
  packages/ui/src/components/renderComponents.tsx
  packages/ui/src/index.ts
  packages/ui/src/types/server-driven.ts
  packages/ui/tailwind.config.cjs
  packages/ui/tsconfig.json
  packages/util/.eslintrc.cjs
  packages/util/eslint.config.js
  packages/util/package.json
  packages/util/src/cn.ts
  packages/util/src/index.ts
  packages/util/tailwind.config.cjs
  packages/util/tsconfig.json
  pnpm-lock.yaml
Labels: refactoring, fix

#4 feat: spacingBlock을 추가합니다.
  apps/web/app/page.tsx
  config/libs/tailwind.config.cjs
  docs/ServerDrivenComponent.md
  packages/ui/package.json
  packages/ui/src/components/atom/Button.tsx
  packages/ui/src/components/atom/radio-group/RadioGroup.stories.tsx
  packages/ui/src/components/atom/radio-group/index.tsx
  packages/ui/src/components/atom/spacing-block/SpacingBlock.stories.tsx
  packages/ui/src/components/atom/spacing-block/example.json
  packages/ui/src/components/atom/spacing-block/index.tsx
  packages/ui/src/components/atom/spacing-block/variants.ts
  packages/ui/src/components/atom/typography/Typogrpahy.stories.ts
  packages/ui/src/components/atom/typography/example.json
  packages/ui/src/components/atom/typography/index.tsx
  packages/ui/src/components/atom/typography/variants.ts
  packages/ui/src/components/renderComponents.tsx
  packages/ui/src/index.ts
  packages/ui/src/types/server-driven.ts
  pnpm-lock.yaml
Labels: feat, refactoring

#5 chore: storybook 관련 알림을 수정합니다.
  .github/workflows/build-check.yml
  .github/workflows/chromatic.yml
  .github/workflows/lint-check.yml
  .github/workflows/type-check.yml
  .husky/prepare-commit-msg
  apps/web/package.json
  package.json
  packages/ui/package.json
  packages/ui/src/empty-entry.ts
  packages/ui/vite.config.js
  packages/util/package.json
  packages/util/vite.config.js
  pnpm-lock.yaml
  turbo.json
Labels: chore

#6 feat: ImageSection 컴포넌트를 추가합니다.
  apps/web/package.json
  packages/ui/package.json
  packages/ui/src/components/atom/image-section/ImageSection.stories.tsx
  packages/ui/src/components/atom/image-section/example.json
  packages/ui/src/components/atom/image-section/index.tsx
  packages/ui/src/components/atom/image-section/variants.ts
  packages/ui/src/components/renderComponents.tsx
  packages/ui/src/types/server-driven.ts
  packages/util/package.json
  turbo.json
Labels: feat

#7 chore: ci yml 파일을 수정합니다.
  .github/workflows/build-check.yml
  .github/workflows/chromatic.yml
  .github/workflows/lint-check.yml
  .github/workflows/pr-check.yml
Labels: chore

#8 feat: flex 컴포넌트를 추가합니다.
  packages/ui/package.json
  packages/ui/src/components/atom/flex/Flex.stories.tsx
  packages/ui/src/components/atom/flex/example.json
  packages/ui/src/components/atom/flex/index.tsx
  packages/ui/src/components/atom/flex/variants.ts
  packages/ui/src/components/renderComponents.tsx
  packages/ui/src/types/server-driven.ts
Labels: feat

#9 feat: 공용 버튼 컴포넌트를 추가합니다.
  config/libs/tailwind.config.cjs
  packages/ui/package.json
  packages/ui/src/components/atom/button/OutlinedButton.stories.tsx
  packages/ui/src/components/atom/button/OutlinedButton.tsx
  packages/ui/src/components/atom/button/SolidButton.stories.tsx
  packages/ui/src/components/atom/button/SolidButton.tsx
  packages/ui/src/components/atom/button/TextButton.stories.tsx
  packages/ui/src/components/atom/button/TextButton.tsx
  packages/ui/src/components/atom/button/example.json
  packages/ui/src/components/atom/button/index.tsx
  packages/ui/src/components/atom/button/variants.ts
  packages/ui/src/components/atom/typography/index.tsx
  packages/ui/src/components/atom/typography/variants.ts
  packages/ui/src/components/renderComponents.tsx
  packages/ui/src/styles/globals.css
  packages/ui/src/types/server-driven.ts
  pnpm-lock.yaml
Labels: feat

#10 feat: Badge 공용 컴포넌트를 추가합니다
  packages/ui/package.json
  packages/ui/src/components/atom/badge/Badge.stories.tsx
  packages/ui/src/components/atom/badge/example.json
  packages/ui/src/components/atom/badge/index.tsx
  packages/ui/src/components/atom/badge/variants.ts
  packages/ui/src/components/renderComponents.tsx
  packages/ui/src/types/server-driven.ts
  pnpm-lock.yaml
Labels: feat

#13 feat: ProgressBar 공용 컴포넌트를 추가합니다.
  packages/ui/package.json
  packages/ui/src/components/atom/progress-bar/ProgressBar.stories.tsx
  packages/ui/src/components/atom/progress-bar/example.json
  packages/ui/src/components/atom/progress-bar/index.tsx
  packages/ui/src/components/atom/progress-bar/variants.ts
  packages/ui/src/components/renderComponents.tsx
  packages/ui/src/types/server-driven.ts
Labels: feat

#14 chore: 스토리북 관련 yml을 변경합니다.
  .github/workflows/chromatic.yml
  apps/web/.storybook/preview.tsx
  apps/web/app/layout.tsx
  apps/web/src/styles/globals.css
  config/libs/globals.css
Labels: chore

#15 chore: Zod에 대한 의존성을 추가합니다.
  package.json
  pnpm-lock.yaml
Labels: chore

#16 feat: icon 컴포넌트를 추가합니다.
  packages/ui/package.json
  packages/ui/src/components/atom/button/OutlinedButton.stories.tsx
  packages/ui/src/components/atom/button/OutlinedButton.tsx
  packages/ui/src/components/atom/button/SolidButton.stories.tsx
  packages/ui/src/components/atom/button/SolidButton.tsx
  packages/ui/src/components/atom/button/TextButton.stories.tsx
  packages/ui/src/components/atom/button/TextButton.tsx
  packages/ui/src/components/atom/button/example.json
  packages/ui/src/components/atom/button/variants.ts
  packages/ui/src/components/atom/icon/Icon.stories.tsx
  packages/ui/src/components/atom/icon/index.tsx
  packages/ui/src/components/atom/icon/variants.ts
  packages/ui/src/components/renderComponents.tsx
  packages/ui/src/types/server-driven.ts
  pnpm-lock.yaml
Labels: feat

#17 feat: PassProductItemBasic 컴포넌트를 추가합니다.
  apps/web/.storybook/main.ts
  apps/web/app/page.tsx
  apps/web/public/avif/placeholder.avif
  packages/ui/package.json
  packages/ui/src/components/atom/image-section/ImageSection.stories.tsx
  packages/ui/src/components/atom/progress-bar/index.tsx
  packages/ui/src/components/molecule/path-product-item/PathProductItemBasic.stories.tsx
  packages/ui/src/components/molecule/path-product-item/PathProductItemBasic.tsx
  packages/ui/src/components/molecule/path-product-item/index.tsx
  packages/ui/src/components/molecule/path-product-item/variants.ts
Labels: feat

#18 feat: TextArea 공용 컴포넌트를 추가합니다.
  packages/ui/package.json
  packages/ui/src/components/atom/text-area/TextArea.stories.tsx
  packages/ui/src/components/atom/text-area/index.tsx
  packages/ui/src/components/atom/text-area/variants.ts
  packages/ui/src/components/atom/typography/index.tsx
  packages/ui/src/components/atom/typography/variants.ts
Labels: feat

#20 chore: pnpm version을 고정시킵니다.
  .npmrc
  pnpm-lock.yaml
Labels: chore

#22 refactor: storybook에서 절대경로를 읽기위해 설정을 변경합니다.
  apps/web/.storybook/main.ts
  apps/web/tsconfig.json
  packages/ui/src/components/atom/badge/Badge.stories.tsx
  packages/ui/src/components/atom/badge/index.tsx
  packages/ui/src/components/atom/button/OutlinedButton.tsx
  packages/ui/src/components/atom/button/SolidButton.stories.tsx
  packages/ui/src/components/atom/button/SolidButton.tsx
  packages/ui/src/components/atom/button/TextButton.stories.tsx
  packages/ui/src/components/atom/button/TextButton.tsx
  packages/ui/src/components/atom/button/index.tsx
  packages/ui/src/components/atom/button/variants.ts
  packages/ui/src/components/atom/flex/Flex.stories.tsx
  packages/ui/src/components/atom/flex/index.tsx
  packages/ui/src/components/atom/icon/index.tsx
  packages/ui/src/components/atom/image-section/ImageSection.stories.tsx
  packages/ui/src/components/atom/image-section/index.tsx
  packages/ui/src/components/atom/progress-bar/ProgressBar.stories.tsx
  packages/ui/src/components/atom/progress-bar/index.tsx
  packages/ui/src/components/atom/radio-group/RadioGroup.stories.tsx
  packages/ui/src/components/atom/spacing-block/SpacingBlock.stories.tsx
  packages/ui/src/components/atom/spacing-block/index.tsx
  packages/ui/src/components/atom/typography/Typogrpahy.stories.ts
  packages/ui/src/components/atom/typography/index.tsx
  packages/ui/src/components/molecule/path-product-item/PathProductItemBasic.stories.tsx
  packages/ui/src/components/molecule/path-product-item/PathProductItemBasic.tsx
  packages/ui/src/components/molecule/path-product-item/variants.ts
  packages/ui/src/components/renderComponents.tsx
  packages/ui/src/types/server-driven.ts
  packages/ui/tsconfig.json
  packages/ui/vite.config.js
Labels: refactoring

#19 feat: PathProductItemProgress 공용 컴포넌트를 추가합니다.
  packages/ui/src/components/atom/image-section/ImageSection.stories.tsx
  packages/ui/src/components/atom/image-section/index.tsx
  packages/ui/src/components/atom/progress-bar/index.tsx
  packages/ui/src/components/molecule/path-product-item/PathProductItemBasic.stories.tsx
  packages/ui/src/components/molecule/path-product-item/PathProductItemBasic.tsx
  packages/ui/src/components/molecule/path-product-item/PathProductItemProgress.stories.tsx
  packages/ui/src/components/molecule/path-product-item/PathProductItemProgress.tsx
  packages/ui/src/components/molecule/path-product-item/index.tsx
Labels: feat

#21 feat: 공용 퍼널 관리 로직을 추가합니다.
  apps/web/src/shared/lib/hooks/use-funnel.tsx
  apps/web/src/types/index.d.ts
Labels: feat

#24 chore: workflow를 통해 라벨을 추가 및 관리합니다.
  .github/workflows/d-day-labeler.yml
  .github/workflows/request-pr-review.yml
  .github/workflows/simple-labeler.yml
Labels: D-3

#25 feat : PathProductAssignment 공용 컴포넌트를 추가합니다.
  apps/web/src/shared/ui/path-product-item/PathProductItemAssignment.stories.tsx
  apps/web/src/shared/ui/path-product-item/PathProductItemAssignment.tsx
  apps/web/src/shared/ui/path-product-item/PathProductItemBasic.tsx
  apps/web/src/shared/ui/path-product-item/PathProductItemProgress.stories.tsx
  apps/web/src/shared/ui/path-product-item/PathProductItemProgress.tsx
  apps/web/src/shared/ui/path-product-item/index.tsx
  apps/web/src/shared/ui/path-product-item/variants.ts
  packages/ui/src/components/badge/index.tsx
Labels: feat

#26 feat: pathDetail Mock 데이터를 추가합니다.
  apps/web/app/path/[pathId]/detail/[pageId]/page.tsx
  apps/web/app/path/[pathId]/introduce/page.tsx
  apps/web/src/__mock__/data/path.ts
  apps/web/src/__mock__/handler/index.ts
  apps/web/src/__mock__/handler/path.ts
  apps/web/src/pages/IntroducePage/IntroducePage.stories.tsx
  apps/web/src/pages/IntroducePage/index.tsx
  apps/web/src/pages/PathDetailPage/PathDetailPage.stories.tsx
  apps/web/src/pages/PathDetailPage/index.tsx
Labels: D-3

#27 feat: PathProductItemDone 컴포넌트를 추가합니다.
  apps/web/src/shared/ui/path-product-item/PathProductItemDone.stories.tsx
  apps/web/src/shared/ui/path-product-item/PathProductItemDone.tsx
  apps/web/src/shared/ui/path-product-item/index.tsx
Labels: feat, D-3

#28 feat: 공용 header, layout 설정을 추가합니다.
  apps/web/app/layout.tsx
  apps/web/app/path/[pathId]/detail/[pageId]/page.tsx
  apps/web/app/path/[pathId]/introduce/page.tsx
  apps/web/app/path/[pathId]/layout.tsx
  apps/web/src/__mock__/data/path.ts
  apps/web/src/pages/IntroducePage/index.tsx
  apps/web/src/shared/ui/header/Header.stories.tsx
  apps/web/src/shared/ui/header/index.tsx
  apps/web/src/shared/ui/logo/Logo.stories.tsx
  apps/web/src/shared/ui/logo/Logo.styles.module.css
  apps/web/src/shared/ui/logo/NaNJauneTRIAL-Regular.subset.ttf
  apps/web/src/shared/ui/logo/index.tsx
  apps/web/src/views/IntroducePage/IntroducePage.stories.tsx
  apps/web/src/views/IntroducePage/index.tsx
  apps/web/src/views/PathDetailPage/PathDetailPage.stories.tsx
  apps/web/src/views/PathDetailPage/index.tsx
  apps/web/tsconfig.json
  config/libs/tailwind.config.cjs
  packages/ui/src/components/button/OutlinedButton.tsx
  packages/ui/src/components/button/SolidButton.tsx
  packages/ui/src/components/button/TextButton.tsx
  packages/ui/src/components/divider/Divider.stories.tsx
  packages/ui/src/components/divider/index.tsx
  packages/ui/src/components/flex/index.tsx
  packages/ui/src/components/icon/variants.ts
  packages/ui/src/components/spacing-block/index.tsx
  packages/ui/src/server.ts
Labels: feat, D-1

#31 fix: 피드백 페이지 Storybook 오류를 해결하였습니다.
  apps/web/app/path/[pathId]/detail/feedback/page.tsx
  apps/web/app/path/[pathId]/feedback/page.tsx
  apps/web/src/shared/lib/utils/index.ts
  apps/web/src/shared/lib/utils/wrap-with-app-router-context.tsx
  apps/web/src/views/FeedbackPage/FeedbackPage.stories.tsx
  apps/web/src/views/FeedbackPage/index.tsx
Labels: fix, D-3

#30 feat: 패스 소개 페이지를 추가합니다.
  apps/web/app/path/[pathId]/introduce/page.tsx
  apps/web/src/__mock__/data/path.ts
  apps/web/src/entities/path/model/path-introduce.ts
  apps/web/src/entities/path/ui/curriculum-bar/CurriculumBar.stories.tsx
  apps/web/src/entities/path/ui/curriculum-bar/index.tsx
  apps/web/src/features/path/ui/path-apply-button/PathApplyButton.stories.tsx
  apps/web/src/features/path/ui/path-apply-button/index.tsx
  apps/web/src/features/path/ui/path-cancle-button/PathCancleButton.stories.tsx
  apps/web/src/features/path/ui/path-cancle-button/index.tsx
  apps/web/src/shared/ui/NavigationLinks/NavigationLinks.stories.tsx
  apps/web/src/shared/ui/NavigationLinks/index.tsx
  apps/web/src/shared/ui/header/Header.stories.tsx
  apps/web/src/shared/ui/logo/Logo.stories.tsx
  apps/web/src/views/IntroducePage/IntroducePage.stories.tsx
  apps/web/src/views/IntroducePage/index.tsx
Labels: feat, D-3

#32 feat: check, radiobtn을 생성합니다.
  apps/web/src/shared/core/sdu/index.tsx
  apps/web/src/shared/core/sdu/radio-group/RadioGroup.stories.tsx
  apps/web/src/shared/core/sdu/radio-group/example.json
  apps/web/src/shared/core/sdu/radio-group/index.tsx
  apps/web/src/shared/core/sdu/server-driven.ts
  config/libs/globals.css
  packages/ui/src/client.ts
  packages/ui/src/components/check-box/CheckBox.stories.tsx
  packages/ui/src/components/check-box/index.tsx
  packages/ui/src/components/check-box/variants.ts
  packages/ui/src/components/check/Check.stories.tsx
  packages/ui/src/components/check/index.tsx
  packages/ui/src/components/icon/variants.ts
  packages/ui/src/components/radio-btn/RadioBtn.stories.tsx
  packages/ui/src/components/radio-btn/index.tsx
  packages/ui/src/server.ts
Labels: feat, D-3

#34 feat: 메인 페이지 퍼블리싱 1차
  apps/web/app/page.tsx
  apps/web/src/__mock__/data/main.ts
  apps/web/src/__mock__/handler/index.ts
  apps/web/src/__mock__/handler/main.ts
  apps/web/src/shared/ui/pagination-controls/PaginationControls.stories.tsx
  apps/web/src/shared/ui/pagination-controls/index.tsx
  apps/web/src/shared/ui/path-product-item/PathProductItemAssignment.stories.tsx
  apps/web/src/shared/ui/path-product-item/PathProductItemBasic.stories.tsx
  apps/web/src/shared/ui/path-product-item/PathProductItemBasic.tsx
  apps/web/src/shared/ui/path-product-item/PathProductItemDone.stories.tsx
  apps/web/src/shared/ui/path-product-item/PathProductItemProgress.stories.tsx
  apps/web/src/shared/ui/path-product-item/PathProductItemProgress.tsx
  apps/web/src/views/MainPage/MainPage.stories.tsx
  apps/web/src/views/MainPage/index.tsx
  apps/web/src/widgets/main/ui/assignment-list/AssignmentList.stories.tsx
  apps/web/src/widgets/main/ui/assignment-list/index.tsx
  apps/web/src/widgets/main/ui/leaning-summary-list/LeaningSummaryList.stories.tsx
  apps/web/src/widgets/main/ui/leaning-summary-list/index.tsx
  apps/web/src/widgets/main/ui/open-soon-path-list/OpenSoonPathList.stories.tsx
  apps/web/src/widgets/main/ui/open-soon-path-list/index.tsx
  apps/web/src/widgets/main/ui/recruiting-path-list/RecruitingPathList.stories.tsx
  apps/web/src/widgets/main/ui/recruiting-path-list/index.tsx
  packages/ui/src/components/icon/variants.ts
Labels: feat, D-3

#35 feat: 메인 페이지 퍼블리싱 완료합니다.
  apps/web/src/__mock__/data/main.ts
  apps/web/src/shared/ui/path-product-item/PathProductItemBasic.tsx
  apps/web/src/widgets/main/ui/assignment-list/index.tsx
  apps/web/src/widgets/main/ui/leaning-summary-list/LeaningSummaryList.stories.tsx
  apps/web/src/widgets/main/ui/leaning-summary-list/index.tsx
  apps/web/src/widgets/main/ui/open-soon-path-list/OpenSoonPathList.stories.tsx
  apps/web/src/widgets/main/ui/open-soon-path-list/index.tsx
  apps/web/src/widgets/main/ui/recruiting-path-list/RecruitingPathList.stories.tsx
  apps/web/src/widgets/main/ui/recruiting-path-list/index.tsx
Labels: feat, D-2

#36 feat: 피드백 페이지 1차 퍼블리싱을 완료합니다.
  apps/web/app/path/[pathId]/detail/[partId]/[pageId]/page.tsx
  apps/web/app/path/[pathId]/detail/[partId]/feedback/loading.tsx
  apps/web/app/path/[pathId]/detail/[partId]/feedback/page.tsx
  apps/web/app/path/[pathId]/feedback/loading.tsx
  apps/web/app/path/[pathId]/feedback/page.tsx
  apps/web/src/__mock__/data/feedback.ts
  apps/web/src/__mock__/handler/path.ts
  apps/web/src/__mock__/types/feedback.ts
  apps/web/src/__mock__/utils/withDelay.ts
  apps/web/src/entities/feedback/lib/apis/get-part-feedback.ts
  apps/web/src/entities/feedback/lib/apis/get-path-feedback.ts
  apps/web/src/entities/feedback/lib/apis/index.ts
  apps/web/src/entities/feedback/lib/hooks/index.ts
  apps/web/src/entities/feedback/lib/hooks/use-get-part-feedback.ts
  apps/web/src/entities/feedback/lib/hooks/use-get-path-feedback.ts
  apps/web/src/entities/feedback/ui/feedback-list/MentoFeedback.tsx
  apps/web/src/entities/feedback/ui/feedback-list/PairFeedback.tsx
  apps/web/src/entities/feedback/ui/feedback-list/PartFeedback.tsx
  apps/web/src/entities/feedback/ui/feedback-list/PathFeedback.tsx
  apps/web/src/entities/feedback/ui/feedback-list/index.ts
  apps/web/src/features/feedback/index.ts
  apps/web/src/features/feedback/lib/apis/index.ts
  apps/web/src/features/feedback/lib/apis/post-part-feedback.ts
  apps/web/src/features/feedback/lib/apis/post-path-feedback.ts
  apps/web/src/features/feedback/lib/hooks/index.ts
  apps/web/src/features/feedback/lib/hooks/use-submit-part-feedback.ts
  apps/web/src/features/feedback/lib/hooks/use-submit-path-feedback.ts
  apps/web/src/features/feedback/ui/part-feedback-submit-button/PartFeedbackSubmitButton.stories.tsx
  apps/web/src/features/feedback/ui/part-feedback-submit-button/index.tsx
  apps/web/src/features/feedback/ui/path-feedback-submit-button/PathFeedbackSubmitButton.stories.tsx
  apps/web/src/features/feedback/ui/path-feedback-submit-button/index.tsx
  apps/web/src/shared/config/constants/http.ts
  apps/web/src/views/PartFeedbackPage/PartFeedbackPage.stories.tsx
  apps/web/src/views/PartFeedbackPage/index.tsx
  apps/web/src/views/PathFeedbackPage/PathFeedbackPage.stories.tsx
  apps/web/src/views/PathFeedbackPage/index.tsx
  apps/web/src/widgets/feedback/config/likert-scale.ts
  apps/web/src/widgets/feedback/ui/feedback-list/index.tsx
  packages/ui/src/components/text-area/index.tsx
Labels: feat, D-1

#38 feat: 메인페이지 msw 로직을 추가합니다
  apps/web/app/loading.tsx
  apps/web/app/page.tsx
  apps/web/src/__mock__/data/main.ts
  apps/web/src/__mock__/handler/main.ts
  apps/web/src/__mock__/types/main.ts
  apps/web/src/entities/main/lib/apis/get-main-data.ts
  apps/web/src/views/MainPage/MainPage.stories.tsx
  apps/web/src/views/MainPage/index.tsx
Labels: feat, D-2

#40 refactor: navigation link를 수정합니다.
  apps/web/.storybook/main.ts
  apps/web/package.json
  apps/web/src/shared/ui/NavigationLinks/NavigationLinks.stories.tsx
  apps/web/src/shared/ui/NavigationLinks/index.tsx
  apps/web/src/views/IntroducePage/index.tsx
  packages/ui/src/components/check/index.tsx
  pnpm-lock.yaml
Labels: refactoring, D-3

#41 refactor: size를 변경합니다.
  .github/workflows/pr-check.yml
  .husky/pre-push
  apps/web/src/shared/ui/NavigationLinks/NavigationLinks.stories.tsx
  apps/web/src/shared/ui/header/index.tsx
  apps/web/src/shared/ui/layout/full-screen-layout.tsx
  apps/web/src/shared/ui/path-product-item/PathProductItemAssignment.tsx
  apps/web/src/shared/ui/path-product-item/PathProductItemBasic.tsx
  apps/web/src/shared/ui/path-product-item/PathProductItemDone.tsx
  apps/web/src/shared/ui/path-product-item/PathProductItemProgress.tsx
  apps/web/src/views/IntroducePage/index.tsx
  apps/web/src/views/MainPage/index.tsx
  apps/web/src/widgets/feedback/ui/likert-scale/index.tsx
  apps/web/src/widgets/main/ui/assignment-list/index.tsx
  apps/web/src/widgets/main/ui/leaning-summary-list/index.tsx
  apps/web/src/widgets/main/ui/open-soon-path-list/index.tsx
  apps/web/src/widgets/main/ui/recruiting-path-list/index.tsx
  config/libs/tailwind.config.cjs
  packages/ui/src/components/check-box/CheckBox.stories.tsx
  packages/ui/src/components/check-box/variants.ts
  packages/ui/src/components/check/Check.stories.tsx
  packages/ui/src/components/check/index.tsx
  packages/ui/src/components/divider/Divider.stories.tsx
  packages/ui/src/components/flex/Flex.stories.tsx
  packages/ui/src/components/flex/index.tsx
  packages/ui/src/components/flex/variants.ts
  packages/ui/src/components/icon/Icon.stories.tsx
  packages/ui/src/components/icon/index.tsx
  packages/ui/src/components/icon/variants.ts
  packages/ui/src/components/progress-bar/index.tsx
  packages/ui/src/components/spacing-block/SpacingBlock.stories.tsx
  packages/ui/src/components/spacing-block/index.tsx
  packages/ui/src/components/spacing-block/variants.ts
  packages/ui/src/variants/size.ts
Labels: refactoring, D-0

#42 refactor: 소개 페이지에 피드백 내용을 반영합니다.
  apps/web/app/path/[pathId]/introduce/loading.tsx
  apps/web/app/path/[pathId]/introduce/page.tsx
  apps/web/src/__mock__/data/path.ts
  apps/web/src/__mock__/handler/path.ts
  apps/web/src/entities/path/lib/apis/get-path-introduce.ts
  apps/web/src/entities/path/lib/apis/index.ts
  apps/web/src/entities/path/lib/types/introduce.ts
  apps/web/src/entities/path/model/path-introduce.ts
  apps/web/src/entities/path/ui/curriculum-bar/CurriculumBar.stories.tsx
  apps/web/src/entities/path/ui/curriculum-bar/index.tsx
  apps/web/src/features/path/ui/path-apply-button/PathApplyButton.stories.tsx
  apps/web/src/features/path/ui/path-apply-button/index.tsx
  apps/web/src/features/path/ui/path-cancle-button/index.tsx
  apps/web/src/shared/core/sdu/ServerDrivenComponent.tsx
  apps/web/src/shared/core/sdu/ServerDrivenFunction.ts
  apps/web/src/shared/core/sdu/button/CustomButton.stories.tsx
  apps/web/src/shared/core/sdu/button/example.json
  apps/web/src/shared/core/sdu/button/index.tsx
  apps/web/src/shared/core/sdu/heading1/index.tsx
  apps/web/src/shared/core/sdu/heading2/index.tsx
  apps/web/src/shared/core/sdu/heading3/index.tsx
  apps/web/src/shared/core/sdu/index.tsx
  apps/web/src/shared/core/sdu/paragraph/index.tsx
  apps/web/src/shared/core/sdu/radio-group/example.json
  apps/web/src/shared/core/sdu/server-driven.ts
  apps/web/src/shared/core/sdu/toggle/index.tsx
  apps/web/src/types/common.ts
  apps/web/src/views/IntroducePage/IntroducePage.stories.tsx
  apps/web/src/views/IntroducePage/index.tsx
  apps/web/src/widgets/path/ui/path-curriculum/CurriculumBar.tsx
  apps/web/src/widgets/path/ui/path-curriculum/CurriculumContent.tsx
  apps/web/src/widgets/path/ui/path-curriculum/PathCurriculum.stories.tsx
  apps/web/src/widgets/path/ui/path-curriculum/index.tsx
  apps/web/src/widgets/path/ui/path-information-banner/PathInformationBanner.stories.tsx
  apps/web/src/widgets/path/ui/path-information-banner/index.tsx
  apps/web/src/widgets/path/ui/path-radio-group/RadioGroup.stories.tsx
  apps/web/src/widgets/path/ui/path-radio-group/index.tsx
  apps/web/src/widgets/path/ui/path-title-banner/PathTitleBanner.stories.tsx
  apps/web/src/widgets/path/ui/path-title-banner/index.tsx
  packages/ui/src/components/icon/variants.ts
  packages/util/src/formatDate.ts
Labels: refactoring, D-2

#43 feat: SDU 컴포넌트를 추가합니다.
  apps/web/src/__mock__/data/path.ts
  apps/web/src/entities/path/lib/types/introduce.ts
  apps/web/src/shared/core/sdu/README.md
  apps/web/src/shared/core/sdu/ServerDrivenComponent.tsx
  apps/web/src/shared/core/sdu/bookmark/Bookmark.stories.tsx
  apps/web/src/shared/core/sdu/bookmark/example.json
  apps/web/src/shared/core/sdu/bookmark/index.tsx
  apps/web/src/shared/core/sdu/bulleted-list-item/BulletedListItem.stories.tsx
  apps/web/src/shared/core/sdu/bulleted-list-item/example.json
  apps/web/src/shared/core/sdu/bulleted-list-item/index.tsx
  apps/web/src/shared/core/sdu/callout/Callout.stories.tsx
  apps/web/src/shared/core/sdu/callout/example.json
  apps/web/src/shared/core/sdu/callout/index.tsx
  apps/web/src/shared/core/sdu/divider/Divider.stories.tsx
  apps/web/src/shared/core/sdu/divider/example.json
  apps/web/src/shared/core/sdu/divider/index.tsx
  apps/web/src/shared/core/sdu/file/File.stories.tsx
  apps/web/src/shared/core/sdu/file/example.json
  apps/web/src/shared/core/sdu/file/index.tsx
  apps/web/src/shared/core/sdu/heading1/Heading1.stories.tsx
  apps/web/src/shared/core/sdu/heading1/example.json
  apps/web/src/shared/core/sdu/heading1/index.tsx
  apps/web/src/shared/core/sdu/heading2/Heading2.stories.tsx
  apps/web/src/shared/core/sdu/heading2/example.json
  apps/web/src/shared/core/sdu/heading2/index.tsx
  apps/web/src/shared/core/sdu/heading3/Heading3.stories.tsx
  apps/web/src/shared/core/sdu/heading3/example.json
  apps/web/src/shared/core/sdu/heading3/index.tsx
  apps/web/src/shared/core/sdu/image/Image.stories.tsx
  apps/web/src/shared/core/sdu/image/example.json
  apps/web/src/shared/core/sdu/image/index.tsx
  apps/web/src/shared/core/sdu/numbered-list-item/Numbered.stories.tsx
  apps/web/src/shared/core/sdu/numbered-list-item/example.json
  apps/web/src/shared/core/sdu/numbered-list-item/index.tsx
  apps/web/src/shared/core/sdu/paragraph/Paragraph.stories.tsx
  apps/web/src/shared/core/sdu/paragraph/example.json
  apps/web/src/shared/core/sdu/paragraph/index.tsx
  apps/web/src/shared/core/sdu/quote/Quote.stories.tsx
  apps/web/src/shared/core/sdu/quote/example.json
  apps/web/src/shared/core/sdu/quote/index.tsx
  apps/web/src/shared/core/sdu/toggle/Toggle.stories.tsx
  apps/web/src/shared/core/sdu/toggle/example.json
  apps/web/src/shared/core/sdu/toggle/index.tsx
  apps/web/src/shared/types/common.ts
  apps/web/src/shared/types/index.d.ts
  apps/web/src/views/IntroducePage/index.tsx
  apps/web/src/widgets/path/ui/path-curriculum/CurriculumBar.tsx
  apps/web/src/widgets/path/ui/path-curriculum/CurriculumContent.tsx
  apps/web/src/widgets/path/ui/path-curriculum/index.tsx
  packages/ui/src/components/icon/variants.ts
  packages/ui/src/components/typography/index.tsx
  packages/ui/src/components/typography/variants.ts
  packages/util/src/get-file-icon.ts
Labels: feat, D-1

#44 feat: 공용 floating 컴포넌트를 추가합니다.
  apps/web/app/path/[pathId]/detail/[partId]/layout.tsx
  apps/web/public/webp/1on1chat.webp
  apps/web/src/shared/ui/floating-action/FloatingAction.stories.tsx
  apps/web/src/shared/ui/floating-action/index.tsx
Labels: feat, D-3

#45 feat: 마이페이지 퍼블리싱 2차 + Tabs 공용 컴포넌트 추가
  apps/web/src/__mock__/data/mypage.ts
  apps/web/src/shared/ui/dropdown-menu/index.tsx
  apps/web/src/shared/ui/pagination/Pagination.stories.tsx
  apps/web/src/shared/ui/pagination/index.tsx
  apps/web/src/shared/ui/tabs/Tabs.stories.tsx
  apps/web/src/shared/ui/tabs/index.tsx
  apps/web/src/views/MyPage/index.tsx
  apps/web/src/widgets/mypage/ui/assignment-list/index.tsx
  apps/web/src/widgets/mypage/ui/feedback-list-section/FeedbackListSection.stories.tsx
  apps/web/src/widgets/mypage/ui/feedback-list-section/index.tsx
  apps/web/src/widgets/mypage/ui/feedback-list/FeedbackList.stories.tsx
  apps/web/src/widgets/mypage/ui/feedback-list/index.tsx
Labels: feat, D-2

#46 feat: 공용 모달 컴포넌트를 추가합니다.
  apps/web/app/layout.tsx
  apps/web/public/svg/success.svg
  apps/web/public/webp/error.webp
  apps/web/public/webp/success.webp
  apps/web/src/shared/ui/portal/Portal.tsx
  apps/web/src/shared/ui/portal/index.tsx
  apps/web/src/shared/ui/portal/modal/CommonModal.stories.tsx
  apps/web/src/shared/ui/portal/modal/CommonModal.tsx
  packages/ui/src/client.ts
  packages/ui/src/components/icon/variants.ts
  packages/ui/src/components/modal/Modal.stories.tsx
  packages/ui/src/components/modal/index.tsx
  packages/ui/src/server.ts
Labels: D-2

#47 feat: 공용 페이지네이션 컴포넌트를 추가합니다.
  packages/ui/src/client.ts
  packages/ui/src/components/pagination/Pagination.stories.tsx
  packages/ui/src/components/pagination/index.tsx
Labels: feat, D-3

#51 fix: 페이지네이션 로직 오류를 수정합니다.
  apps/web/src/widgets/mypage/ui/feedback-list/index.tsx
  packages/ui/src/components/pagination/Pagination.stories.tsx
  packages/ui/src/components/pagination/index.tsx
Labels: D-2

#53 feat: QuestionListSection 영역 퍼블리싱을 완료합니다.
  apps/web/src/__mock__/data/question.ts
  apps/web/src/__mock__/types/question.ts
  apps/web/src/entities/question/ui/question-list/index.tsx
  apps/web/src/features/feedback/ui/part-feedback-submit-button/PartFeedbackSubmitButton.stories.tsx
  apps/web/src/features/feedback/ui/path-feedback-submit-button/PathFeedbackSubmitButton.stories.tsx
  apps/web/src/features/quesion/ui/filter-answered-questions/FilterAnsweredQuestions.stories.tsx
  apps/web/src/features/quesion/ui/filter-answered-questions/index.tsx
  apps/web/src/features/quesion/ui/question-search-bar/QuestionSearchBar.stories.tsx
  apps/web/src/features/quesion/ui/question-search-bar/index.tsx
  apps/web/src/views/QuestionListPage/QuestionListPage.stories.tsx
  apps/web/src/views/QuestionListPage/index.tsx
  apps/web/src/widgets/question/ui/one-question-preview/OneQuestionPreview.stories.tsx
  apps/web/src/widgets/question/ui/one-question-preview/index.tsx
  packages/ui/src/components/badge/index.tsx
  packages/ui/src/components/badge/variants.ts
  packages/ui/src/components/icon/variants.ts
  packages/ui/src/components/input/index.tsx
Labels: D-2

#54 feat: PathDeatailSideNavbar를 추가합니다.
  apps/web/app/path/[pathId]/detail/[partId]/[pageId]/page.tsx
  apps/web/app/path/[pathId]/detail/layout.tsx
  apps/web/app/path/[pathId]/detail/loading.tsx
  apps/web/app/path/[pathId]/detail/page.tsx
  apps/web/app/path/[pathId]/load/loading.tsx
  apps/web/app/path/[pathId]/load/page.tsx
  apps/web/app/path/[pathId]/loading.tsx
  apps/web/app/path/[pathId]/page.tsx
  apps/web/src/__mock__/data/path.ts
  apps/web/src/__mock__/handler/path.ts
  apps/web/src/entities/path/lib/apis/get-path-introduce.ts
  apps/web/src/entities/path/lib/apis/get-path-load.ts
  apps/web/src/entities/path/lib/apis/get-path-page.ts
  apps/web/src/entities/path/lib/apis/get-path-sidebar-status.ts
  apps/web/src/entities/path/lib/apis/index.ts
  apps/web/src/entities/path/lib/types/apis.ts
  apps/web/src/entities/path/lib/types/introduce.ts
  apps/web/src/entities/path/model/path-detail.ts
  apps/web/src/entities/path/ui/path-quiz/index.tsx
  apps/web/src/shared/config/constants/end-point.ts
  apps/web/src/shared/config/constants/querykey.ts
  apps/web/src/shared/ui/floating-action/FloatingAction.stories.tsx
  apps/web/src/views/IntroducePage/index.tsx
  apps/web/src/views/PathDetailPage/PathDetailPage.stories.tsx
  apps/web/src/views/PathDetailPage/index.tsx
  apps/web/src/widgets/path/ui/path-curriculum/PathCurriculum.stories.tsx
  apps/web/src/widgets/path/ui/path-detail-nav-link/CheckCurriculumBlock.tsx
  apps/web/src/widgets/path/ui/path-detail-nav-link/InformationBlock.tsx
  apps/web/src/widgets/path/ui/path-detail-nav-link/index.tsx
  apps/web/src/widgets/path/ui/path-information-banner/PathInformationBanner.stories.tsx
  apps/web/src/widgets/path/ui/path-title-banner/PathTitleBanner.stories.tsx
  packages/ui/src/components/icon/variants.ts
Labels: feat, D-1
